//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Champions.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        public Team()
        {
            this.Attendant = new HashSet<Attendant>();
            this.Winner = new HashSet<Winner>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
    
        public virtual ICollection<Attendant> Attendant { get; set; }
        public virtual ICollection<Winner> Winner { get; set; }
    }
}
